// src/components/About.js
// maybe rethink how the text is phrased about me.
import "./styling/About.css"

export default function About() {
	return (
		<section id="About" className="AboutContainer">
			<h2 id="HeaderScrollTo"></h2>
			<br />
			<h2 className="AboutmeHeader" id="AboutmeHeader">About Me</h2>
			<p>Borned and raised in Stockholm, Sweden, moved to Glasgow in 2018 to proceed with higher education. 
            I enjoy using machine learning and data analysis for personal projects, as it lets me explore data and learn new insights.
            My current project is centered on fine-tuning LLM models to distinguish between text generated by large language models and text written by humans, with the aim of addressing plagiarism.
            </p>
		</section>
	);
}
